# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.29 on 2020-06-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.11.29 on 2020-06-11 09:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> Начальный коммит


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Person',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
=======
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.FloatField(validators=[django.core.validators.MinValueValidator(0.9)])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payout', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('payout_status', models.BooleanField(default=False)),
                ('amount_num', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
>>>>>>> Начальный коммит
                ('tel_num', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='payout',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payout.Person'),
        ),
        migrations.AddField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payout.Person'),
        ),
>>>>>>> Начальный коммит
    ]
