# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_auto_20200608_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payout', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now=True)),
                ('payout_date', models.DateTimeField(auto_now=True)),
                ('payout_status', models.BooleanField(default=False)),
                ('amount_num', models.CharField(blank=True, max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payout.Person')),
            ],
        ),
    ]
